services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: reflecto-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      #- DATABASE_URL=postgresql://reflecto_user:reflecto_pass@postgres:5432/reflecto_db?schema=reflecto-ai-2
      - DATABASE_URL=postgresql://samiksha_user:Samiksha%407896@host.docker.internal:5432/samiksha_prod?schema=reflecto-ai-2
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: reflecto-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./apps/frontend/.env.production
    depends_on:
      - backend
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: reflecto-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reflecto_user
      POSTGRES_PASSWORD: reflecto_pass
      POSTGRES_DB: reflecto_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
